#testing on 3.0.54 with Rediss
#slanger issue
import:
- stages.yml
- ifs.yml
- ifs-with-envs.yml
- secure.yml
- sleep.yml

os: linux
dist: focal
language: ruby
addons:
  apt:
    packages:
      - ca-certificates
rvm:
- 2.7.5
jobs:
  allow_failures:
  - os: linux
    dist: focal
    language: ruby
    rvm: 2.7.5
#testing again
