os: linux
dist: focal

language: minimal

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
    - $HOME/.cache/pip

notifications:
  email:
    on_success: change
    on_failure: always

jobs:
  include:
    - name: "Python 3.9"
      language: python
      python: "3.9"
      install:
        - pip install -r requirements.txt
      script:
        - pytest

    - name: "Python 3.10"
      language: python
      python: "3.10"
      install:
        - pip install -r requirements.txt
      script:
        - pytest

    - name: "Node.js 14"
      language: node_js
      node_js: "14"
      install:
        - npm install
      script:
        - npm test

    - name: "Node.js 16"
      language: node_js
      node_js: "16"
      install:
        - npm install
      script:
        - npm test

    - name: "Java 8"
      language: java
      jdk: openjdk8
      install:
        - mvn install
      script:
        - mvn test

    - name: "Java 11"
      language: java
      jdk: openjdk11
      install:
        - mvn install
      script:
        - mvn test

    - name: "Ruby 2.7"
      language: ruby
      rvm: 2.7
      install:
        - bundle install
      script:
        - rake test

    - name: "Ruby 3.0"
      language: ruby
      rvm: 3.0
      install:
        - bundle install
      script:
        - rake test

    - name: "PHP 7.4"
      language: php
      php: "7.4"
      install:
        - composer install
      script:
        - phpunit

    - name: "PHP 8.0"
      language: php
      php: "8.0"
      install:
        - composer install
      script:
        - phpunit

    - name: "Go 1.16"
      language: go
      go: "1.16"
      install:
        - go get -v ./...
      script:
        - go test ./...

    - name: "Go 1.17"
      language: go
      go: "1.17"
      install:
        - go get -v ./...
      script:
        - go test ./...

    - name: "Rust Stable"
      language: rust
      rust: stable
      install:
        - cargo build
      script:
        - cargo test

    - name: "Rust Beta"
      language: rust
      rust: beta
      install:
        - cargo build
      script:
        - cargo test
