#jobs:
#include:
#- stage: "Test draft"
#if: env(TRAVIS_PULL_REQUEST_IS_DRAFT) != "true"
#script: echo $TRAVIS_PULL_REQUEST_IS_DRAFT
#
os: linux
dist: focal
language: shell

install: skip
script: sleep 20

jobs:
  include:
    - if: env(TRAVIS_PULL_REQUEST_IS_DRAFT) IS present
      script: echo "I am in PR Draft"
    - script: sleep 10
