#testing on 3.0.54 with Rediss
#slanger issue
#testing
import:
- stages.yml
- ifs.yml
- ifs-with-envs.yml
- secure.yml
- sleep.yml

arch: s390x
os: linux
dist: focal
language: ruby

rvm:
- 2.7.5
jobs:
  allow_failures:
  - os: linux
    dist: focal
    language: ruby
    rvm: 2.7.5
#testing again
