import:
- vault.yml
branches:
  only:
  - main
  - integration-regresion-tests
  - vault-tests
dist: bionic
language: ruby
vault:
  api_url: vault-east.staging.travis-ci.org
  token:
    secure: "KEy8Nyf9oXf4A2ngZ24WKC1qiyqqlvw+j6Cn0V4BTbry4WEQV0YYcJfS2ex75LJ7JsloKxkjhZDksTUnnlMW0VUyLLi5vkPQaoyLqXNAh1YcLhXsEzDJu/s614FRUkm9B0vS7IM0sEk8kA5eKwQ6q5gNlPsTBPLaavCLKq0DExOPnopWupc/T35MoLk0MXVgeV39BthT0dV4BtAkE9BhoCaBTPHV0KfO4RCdW//wRgMQ8JU/LGvJpMI7sUn9Ase/Xu5h8IhIXPo3xz6SGQFqkzE0Ni8eomaLIwLB5XAu0YE0e2YhZVt/xjIF4tIw1dzH0ta5ThMNIDfUg03iguw+wTLDr8XBSB/kSmd4LBGdNJIC1HhDB7dHLCaJxqMhGgUQrXCDf8Kv8nipFpdwWcBk9gvbh7dwuYizQjFR4pRtbd9Xw2xMxdJy2uiYPrXmLAqSj+zzmPxdb0KUKowu7N8l+iNSLu0zroh0yJexS7Csfe1ov2cZpMf8aMmgeBswrWqGAo5UV9nKw8FqGIcovuRalvcQNjVW/DWMCu6q1UlglX/9SwHNFtV/JrnrSFi9ED+wJ07R1MRsnve+yyX0iRaR4FK3U02Jt6xi2xOn8a/fMjom9WGcJbooKwUE9aXCOymWS9UNYFH5DdsfV3zso6AzNMKKbZbLzjV0rQOFdzCL7wU="
  secrets:
    - namespace:
        - name: ns1
        - project_id/secret_key_a
        - project_id/not_existent
    - ns2/project_id/secret_key_b
    - ns2/project_id/not_existent_key
script: ruby ./source/vault_check.rb
env:
  global:
  - secure: J6PkiwYONd/W1PB5FOtJ46i6Ta7MGx05znAVGcW5E5jDDPBMuOL8Ecq/0vlbPsFGPlwHZtnn4FjWtg7X183gWtRZ0eGdY6GE/5hzL1g65aw0XyLXBSRzu5R2IQYlbNDxclXjBhVV7NvH4z63EFSKkbaxVuuUQXDbNXjgEJDMXfAQqSxlz/+0Qh/yJNvsJRnG3soT3c0fHa839k32yqjIGJqO5VJDEp8O5sRaEIbTqF4v6PwkKDY58MAfrNFMWuMxfzUAAQj2bt1S5E9baajv2rllJgS/i9gNFO5XKoVGQN3UbFI1rpR+oGc4nWn6gdHpoLA1j5aMyLVHw3dgKrv5OyysOP+kF0T8sgY0P3WThNJxwK8NKMymUcjCx9mmu+ZHxA9qZHGPBf6lbzVpF9XeOn7BXpwD10dFOlPEYgKqAuiecNVnXHFtr42LJryYZJpL/DjP8BdMaaH24jaNZDpUQw147cpcpZXvHv+LQjUpRQSxQx+iLO2SoEzdg7fHYoIAbGO9tZB1j/uS+4JYTQv7WJKam84iUkM74FF2l3JHU0zjdT5sb0qU91aUAHDUuvV4t997ngE/rMw22scKbVGQtVsDiMYEBbfqX3wnFwCSnlYfn9dJEU/pPjlS/qaxcehvGxII5TJMZtjBFYIgApo5koAn0S6G1jH1CcvMRDH5m9A=
